- name: Install software
  hosts: localhost
  vars:
    brew_packages:
      - python
      - ansible
      - openssl
      - gh
      - git
      - jq
      - mas
      - awscli
      - azure-cli
      - vault
      - telnet
      - terraform
      - wget
    cask_apps:
      - bettertouchtool
      - blockblock
      - calibre
      - do-not-disturb
      - google-cloud-sdk
      - google-drive
      - lulu
      - oversight
      - monitorcontrol
      - powershell
      - private-internet-access
      - sonos
      - visual-studio-code
      - vlc
      - wireshark
    mas_apps:
      - { id: 1142578753, name: "OmniGraffle 7" }
      - { id: 1352778147, name: "Bitwarden" }
      - { id: 1295203466, name: "Microsoft Remote Desktop" }

  tasks:
    - name: Install homebrew packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
    - name: Install homebrew casks
      homebrew_cask:
        name: "{{ cask_apps }}"
        state: present
        accept_external_apps: True
